# MAIN base
baseURL = "https://eclate.us"
languageCode = "en-us"
title = "Eclate | Technology Consulting"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Services"
    url = "#service"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Latest Article"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "Chicago, IL"
email = "ali@eclate.us"
phone = "+1 (339) 298 7523"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/eclate"
twitter = "https://twitter.com/eclate"
github = "https://github.com/eclate"

[params]

# Header
logo = "images/logo.png"
fabFormURL = "https://fabform.io/f/Vid7gYO"
googleAnalytics = "UA-175025671-2"
favicon = "images/favicon.ico"
# Footer
footerTitle = "Your trusted partner"
copyright1 = "All right reserved"
copyright2 = "Copyright ©  {year}"

#contact
email = "ali@eclate.us"
